import random 
n=random.randint(1,12)
if(n==1):
    print("jan")
elif(n==2):
    print("feb")
elif(n==3):
    print("march")
elif(n==4):
    print("april")
elif(n==5):
    print("may")
elif(n==6):
    print("june")
elif(n==7):
    print("july")
elif(n==8):
    print("aug")
elif(n==9):
    print("sept")
elif(n==10):
    print("oct")
elif(n==11):
    print("nov")
else:
    print("dec")
